### ISSUE TITLE
Reforming Navbar

### ISSUE THREAD

**Issue by mahekkg** [DSC-JSS-NOIDA/blogzen#14]
Hello,
As a contributor participating in GSSoC'23, I would like to improve the website's navbar. Upon reviewing the site, I noticed that the navbar could benefit from enhancements to its functionality and visual appeal.

By improving the navbar, we can achieve the following:

Responsive Design
Visual Enhancements

I'm enthusiastic about contributing to this project and believe that an improved navbar will greatly enhance the user experience. Kindly assign me this task, and I will start working on it promptly.

Thank you!

**Comment by kasturimandlik** [comment]
I would like to work on this under GSSOC'23. please assign me this issue.
