### ISSUE TITLE
Spacing Between cards

### ISSUE THREAD

**Issue by NishantRajhans** [DSC-JSS-NOIDA/blogzen#2]
![Screenshot (15)](https://github.com/DSC-JSS-NOIDA/blogzen/assets/100590061/1a3dcfec-fd37-4e22-a886-76304fb85489)
in this website i found that the space is not maintain between the cards 
i will improve all the spacing and improve the UI of this website using HTML ,CSS, Javascript

**Comment by SyedImtiyaz-1** [comment]
Hello @NishantRajhans,
I have already raised the PR
 ### Check this once #4 👍🏻
