### ISSUE TITLE
improve the cards design

### ISSUE THREAD

**Issue by karthiknadar1204** [DSC-JSS-NOIDA/blogzen#21]

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by Manishak798** [comment]
I will improve the card design using CSS and make the look more decent and attractive. please assign me this issue under GSSOC'23.

**Comment by karthiknadar1204** [comment]
Making the cards more organised by separating them from each other evenly by applying appropriate css styles,ALigning the cards to the center of the page,adding a read button instead of clikcing on the link directly and increasing the font size of the overview about the blog.
These are the changes that i propose along with some additional hover effects

**Comment by anunayandkumar** [comment]
Under GSSoC'23 I would like to improve the overall page by adding animations , fixing orientations etc
