### ISSUE TITLE
Styling and Improving responsiveness of buttons { Gssoc'23 }

### ISSUE THREAD

**Issue by SrishtiSonam** [DSC-JSS-NOIDA/blogzen#226]
Here the buttons include icons of social media in footer, buttons of navbar, the recent and treading button.
Assign this issue to me under GSSOC.

**Comment by shubham725809** [comment]
I can quickly develop these features with better UI because I did these projects in college.

**Comment by chiki012** [comment]
I am able to solve these issues.  please assign me this issue.
