### ISSUE TITLE
Improving Navbar

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [DSC-JSS-NOIDA/blogzen#229]
@rucha0702 , @piug-07  @Atharv-110 , Please assign me this issue as a gssoc'2023 contributor I want to work on this feature
Before Changes -
![Screenshot 2023-05-22 231753](https://github.com/DSC-JSS-NOIDA/blogzen/assets/125626654/e9f46291-e9cb-470e-ad35-af2af803eabe)

After Changes -
![Screenshot 2023-05-22 231608](https://github.com/DSC-JSS-NOIDA/blogzen/assets/125626654/74d9ea0c-daba-4d5c-ae4c-4aed7af3b3f1)

**Comment by Mittalkashish** [comment]
i want to contribute on this issue as GSSOC Contributor . kindly assign it to me

**Comment by AdhiRaj08** [comment]
Please assign this task to me under GSSOC '23.

**Comment by Shefali1804** [comment]
I would like to work on improving the navbar. Please assign me this.

**Comment by Atharv-110** [comment]
@MOHDNEHALKHAN go ahead, Assigned to you.

**Comment by MOHDNEHALKHAN** [comment]
@Atharv-110 Thank You for assigning me
