### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by Nevish-302** [DSC-JSS-NOIDA/blogzen#235]

**Comment by Nevish-302** [comment]
i'd like to make the login page as provided in the design

**Comment by Harleenkaur1712** [comment]
under gssoc23 i would like to contribute my skills and learn

**Comment by krittika2004** [comment]
I would like to contribute in this issue. Kindly assign this to me under gssoc 23

**Comment by Jiyarathore** [comment]
I am interested to work on this issue  GSSoC'23, so please assign me this task.

**Comment by Bharath-KumarReddy** [comment]
i added a login page by clicking the login page button which i changed its style by bootstrap and i made pull request once please check.

**Comment by shubham725809** [comment]
I can develop the login page for this website. please assign me this issue.

**Comment by chiki012** [comment]
I'm able to design the login page. please assign me this issue.

**Comment by sam2003j** [comment]
I would love to design the login page. Please assign this task to me under GsSoc'23.

**Comment by Maryann-01** [comment]
Please assign this issue to me

**Comment by SAUMYXA** [comment]
Hi, I am a contributor at GSSOC'23, kindly assign me this issue. I would like to contribute here.
