### ISSUE TITLE
[GSSoC '23 ]Fix some problems in the HEADER

### ISSUE THREAD

**Issue by PoulavBhowmick03** [DSC-JSS-NOIDA/blogzen#313]
1. Link the logo of Blogzen to it's home page
2. The icon before login and calender isn't loading, I want to fix that
3. Allow cursor pointer and hover effect on the Recent button beside Trending
4. 
![image](https://github.com/DSC-JSS-NOIDA/blogzen/assets/133862694/6df8c3d2-1abe-43b4-adf0-d70470871d7b)

**Comment by Atharv-110** [comment]
Go ahead @PoulavBhowmick03, Assigned it to you.
