### ISSUE TITLE
[GSSoC '23] Create a LOGIN and SIGNUP page

### ISSUE THREAD

**Issue by PoulavBhowmick03** [DSC-JSS-NOIDA/blogzen#314]
The login and sign up buttons in the navbar lead to nowhere. I want to create and a login and signup page to them respectively

**Comment by Siddhant422** [comment]
hey can you assign this issue to me under GSsoc'23.

**Comment by nuragajraj** [comment]
plz give me chance to do the changes under GSSOC contributer 2023'.

**Comment by PoulavBhowmick03** [comment]
@piug-07 can this be assigned? I don't see other issues asking about the same.
