### ISSUE TITLE
 [GSSOC'23] Create card for each blog

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [DSC-JSS-NOIDA/blogzen#330]
Create card for each blog at the home page or on filtering using css. They attractiveness will increase. I can do this work, please assign this issue to me.

A card consists of :- 
1. Picture
2. Heading of the blog
3. Sub-title of the blog (optional)
4. Little content regarding that blog
5. Author of the blog and it's profile picture

With hovering effect.

So, please assign this task to me.

**Comment by Ayushpanditmoto** [comment]
Assign me this task

**Comment by Avdhesh-Varshney** [comment]
Please assign this task to me !

**Comment by Avdhesh-Varshney** [comment]
I am waiting for your response sir...
