### ISSUE TITLE
Add "Scroll to Top" button on UI.

### ISSUE THREAD

**Issue by rayyan016** [DSC-JSS-NOIDA/blogzen#35]
I would like to add a "Scroll to Top" button on UI. Could you please assign me this issue under GSSOC'23?

**Comment by harshita-kaushik2** [comment]
Hello !
As a contributor for GSSoC 2023, I would like to add the "Scroll to Top" button on the UI. 
I have previously worked on this segment in my personal projects and am fully aware of how to make it function smoothly.

Hence, I request you to assign this issue to me. 
Thank you :)
