### ISSUE TITLE
Making Footer/Buttons same on multiple Pages

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [DSC-JSS-NOIDA/blogzen#353]
## Issue

I will be making footer with same css on all the pages across the website.
I will also working on different buttons such as the Calendar Button to make it same on all webpages.

# Screenshots

![image](https://github.com/DSC-JSS-NOIDA/blogzen/assets/85278243/66863a64-a92b-4366-a1b3-fdd7b8ec409f)

![image](https://github.com/DSC-JSS-NOIDA/blogzen/assets/85278243/5f5786d8-65fb-4f9f-b1af-fed8891ebd16)

![image](https://github.com/DSC-JSS-NOIDA/blogzen/assets/85278243/5051218b-1938-4b75-b84b-36e4a67fd2f5)

![image](https://github.com/DSC-JSS-NOIDA/blogzen/assets/85278243/1628f85b-fa82-4950-a0dd-8954316d4e87)

Please assign me this task under GSSOC'23

**Comment by ashutoshrana8118** [comment]
I wanted to work on this pls allow me to contribute on this issues
