### ISSUE TITLE
Fix Navbar for better UX

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [DSC-JSS-NOIDA/blogzen#361]
@Atharv-110 , As a gssoc,2023 contributor I want to add this feature
After Changes, it looks like similar to -
![Screenshot 2023-05-26 232052](https://github.com/DSC-JSS-NOIDA/blogzen/assets/125626654/2077cd64-f187-45c8-8cba-910fa3a8dd3b)

**Comment by MOHDNEHALKHAN** [comment]
@piug-07 , Thank you for assigning me

**Comment by MOHDNEHALKHAN** [comment]
@piug-07, before working on this issue, please review and merged my previous PR No - #357 of issue #229

**Comment by Komal73** [comment]
is this issue still open?

**Comment by MOHDNEHALKHAN** [comment]
@Komal73  , Yes i am working on this issue
