### ISSUE TITLE
Create different pages for Technology, branding, news, AI etc in home page

### ISSUE THREAD

**Issue by PoulavBhowmick03** [DSC-JSS-NOIDA/blogzen#411]
I want to add different blogs regarding Technology, branding, news, AI, management, design in the home page.

**Comment by PoulavBhowmick03** [comment]
Can you please merge https://github.com/DSC-JSS-NOIDA/blogzen/pull/345
so that I can make a PR for this? this assigned task is done
@piug-07

**Comment by Uzmakh** [comment]
I am also interested in this issue.
