### ISSUE TITLE
improving footer

### ISSUE THREAD

**Issue by Komal73** [DSC-JSS-NOIDA/blogzen#450]
the footer is not clear and responsive, I want to contribute to this issue, @Atharv-110 @piug-07 please assign this issue to me.
![Screenshot 2023-05-29 184835](https://github.com/DSC-JSS-NOIDA/blogzen/assets/115211296/9a9d3429-7579-4f8f-8062-89ef328b443b)

**Comment by Uzmakh** [comment]
I am also interested in this issue.

**Comment by Snigdha2712** [comment]
Please assign this project to me. I will fix the issue

**Comment by Kapileswar-Moharana** [comment]
I would like to improve the Footer page. Kindly assign this issue to me under GSSoC23

**Comment by Vaishwanavi** [comment]
I will fix the issue of footer ,please assign this issue to me under GSSOC'23.
