### ISSUE TITLE
Improving the UI

### ISSUE THREAD

**Issue by sumitkr2000** [DSC-JSS-NOIDA/blogzen#46]
Hey @piug-07 Your UI is looking really bad. I want to transform your UI into a whole new look. Please assign me this issue. Thank you!

**Comment by shreya26-bit** [comment]
I want to work on your UI .please assign this issue to me.i will make Your UI more attractive

**Comment by sumitkr2000** [comment]
@shreya26-bit i am already going to work on it. please raise another pr 🙂. Thank you

**Comment by shreya26-bit** [comment]
Okay🙂

**Comment by sumitkr2000** [comment]
@piug-07 please assign me this issue.
