### ISSUE TITLE
adding hover effect and transitions to all the buttons and icons 

### ISSUE THREAD

**Issue by Komal73** [DSC-JSS-NOIDA/blogzen#482]
@piug-07 @Atharv-110 kindly assign this issue to me to contribute under gssoc23

**Comment by its-mahi** [comment]
I want to work on this issue.
Please assign this to me.

**Comment by Diya1418** [comment]
I can work on this issue kindly assign it to me

**Comment by Shefali1804** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by codin-AWMKAR** [comment]
@piug-07  @Atharv-110  Kindly assign this to me as I have added similar features in my portfolio and spotify clone.

**Comment by Komal73** [comment]
@Shefali1804 @Diya1418 @its-mahi kindly DM me on discord so that we can divide our work, my discord I'd is komal#0779

**Comment by janhvii20** [comment]
please assign this issue to me 
I want to work upon it

**Comment by mishba-ai** [comment]
@piug-07 plz assign this issue to me

**Comment by Shefali1804** [comment]
@piug-07 please review and merge my pr
I've added a hover effect to the moon icon in the navbar and also to sec1 #764

**Comment by mishba-ai** [comment]
can you assign this to me?
