### ISSUE TITLE
Enhancement: Add New Sign-Up Page with SVG Animation

### ISSUE THREAD

**Issue by varunshankar07** [DSC-JSS-NOIDA/blogzen#55]
Hi There! Currently, the website lacks a sign-up page, which is essential for user engagement and expanding our user base. To enhance the user experience and make the sign-up process more visually appealing, i propose adding a new sign-up feature with an awesome SVG animation. 🥰☺️

**Features**:🌇🪄

**Sign-Up Form**: Create a user-friendly sign-up form that allows users to enter their relevant information, such as name, email address, and password.

**Form Validation**: Implement client-side form validation to ensure that users provide valid and complete information before submitting the form.

**Password Strength Indicator**: Include a visual indicator to provide feedback on password strength and encourage users to choose stronger passwords.

**SVG Animation**: Develop an impressive SVG animation that will accompany the sign-up form. The animation should be eye-catching, smooth, and visually appealing to create an engaging user experience.

The Finished Sign Up May Look Like This>>This Design Is Personally Designed By Me ✨✨ 

![3](https://github.com/DSC-JSS-NOIDA/blogzen/assets/82266277/49ad7ae5-8587-4eea-9a80-e8c1f5bb4137)

**Comment by Manikantan-S** [comment]
Under GSSOC'23,I would like to work on this project. please assign me this task

**Comment by varunshankar07** [comment]
@Manikantan-S  I have raised this issue because i wanted to  implement this feature on the site and please read the project description carefully before commenting

**Comment by Manikantan-S** [comment]
@varunshankar07 ok
