### ISSUE TITLE
[Bug] Blogs text are overlapping each other. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [DSC-JSS-NOIDA/blogzen#559]
The blogs text are overlapping each other, which is making the text unreadable.
![overlapping](https://github.com/DSC-JSS-NOIDA/blogzen/assets/116020663/1f0da428-7023-4614-b438-9577f316b53f)
Please assign me this issue, I can solve it.

**Comment by 1Shubham7** [comment]
Please assign me this issue under gssoc'23.

**Comment by muskanmandloi** [comment]
please assign it to me
