### ISSUE TITLE
Add login page

### ISSUE THREAD

**Issue by sumitkr2000** [DSC-JSS-NOIDA/blogzen#580]
Hey, I want to add a login page.  My design is ready. Please assign me this issue. Thank you!

**Comment by yash8917** [comment]
I would like to work on this issue pls assign me under the GSSOC '2023

**Comment by Shrejal123** [comment]
I am intersted to work on this issue . Could you please assign it to me.

**Comment by sumitkr2000** [comment]
Please assign me this issue so that I can start working on it.

**Comment by sumitkr2000** [comment]
Please assign me this issue so that I can start working on it.

**Comment by sumitkr2000** [comment]
Please assign me this issue so that I can start working on it.

**Comment by sumitkr2000** [comment]
Please assign me this issue so that I can start working on it.
