### ISSUE TITLE
Removing unwnated box in navbar

### ISSUE THREAD

**Issue by Bharadwajshivam28** [DSC-JSS-NOIDA/blogzen#7]
I have noticed that there are extra box in navbar .. we must remove it

![Screenshot from 2023-05-20 00-39-12](https://github.com/DSC-JSS-NOIDA/blogzen/assets/108119109/43046d7b-10a9-45cd-83ff-9246fc24471f)

Please assign me under GSSOC23

**Comment by JeevarajBoomi** [comment]
I'm GSSoC 23 Contributor, Can you assign me to fix that issue

**Comment by Bharadwajshivam28** [comment]
> I'm GSSoC 23 Contributor, Can you assign me to fix that issue 

I am also contributor so I have opened the issue..like i will work on it

**Comment by Atharv-110** [comment]
@Bharadwajshivam28 assigned it to you.
