### ISSUE TITLE
Hover effect on social media icons

### ISSUE THREAD

**Issue by DivyanshiNarang** [DSC-JSS-NOIDA/blogzen#701]
Adding hover effect on social media icons to make the website more attractive.

<img width="207" alt="Screenshot 2023-06-30 214002" src="https://github.com/DSC-JSS-NOIDA/blogzen/assets/74779601/c8873592-19f0-4dfb-a8dd-c8972d9f33ca">

@piug-07  *Please assign this issue to me under gssoc23*

**Comment by priyagarg1184** [comment]
I'd love to contribute to this issue under gssoc.

**Comment by Dani2003** [comment]
Please Assign this issue to me under gssoc'23
