### ISSUE TITLE
hovering effect 

### ISSUE THREAD

**Issue by khadar1020** [DSC-JSS-NOIDA/blogzen#720]
no hovering effect on the login button and the color change of the calender button does not look good.
![WhatsApp Image 2023-07-03 at 08 46 27](https://github.com/DSC-JSS-NOIDA/blogzen/assets/124120102/2ae0a3c2-8a29-4273-a4d1-eb1bc354a1f0)
![WhatsApp Image 2023-07-03 at 08 46 26](https://github.com/DSC-JSS-NOIDA/blogzen/assets/124120102/6c4245be-6670-4c49-bb65-e80e9f98a1e3)

**Comment by khadar1020** [comment]
I would like to work on it please assign me this issue

**Comment by PiyushK79** [comment]
I would like to work on this issue. I can also add styling and effects for buttons. Please assign this issue to me under Gssoc'23 tag.

**Comment by khadar1020** [comment]
piyushK79 create your own issue I want to work on it
