### ISSUE TITLE
Instagram Clone[GSSOC'23]

### ISSUE THREAD

**Issue by apu52** [DSC-JSS-NOIDA/blogzen#741]
h1 align="center">Instagram Clone</h1>

<div align="center">
<br>
<h2 align="center">Hi Sir👋, Here is my project of INSTA CLONE </h2>

<p>I am Arpan Chowdhury, a aspiring Web developer.🤖 Here is the project of the front-end Web Developement. We all use the most famous social media platform INSTAGRAM. So, here is the frontend clone of the landing page👆🏻 .</p>

# Screenshot
![Screenshot 2023-06-17 191450](https://github.com/apu52/InstaClone/assets/114172928/d2b4ba78-1442-436d-8f61-1b7d12bb132c)

**Comment by apu52** [comment]
@piug-07 Please assign me the issue under **GSSOC'23**.

**Comment by Jyoticharan** [comment]
can I work on the issue
