### ISSUE TITLE
Add scroll to top button

### ISSUE THREAD

**Issue by sumitkr2000** [DSC-JSS-NOIDA/blogzen#755]
Hey, I want to add scroll to top button to your website. Please assign me this issue. Thank you!

**Comment by SoumyaBehura18** [comment]
Hello,I want to add scroll to top button.Please kindly assign me this issue.Thanks!

**Comment by ShrutiSingh04503** [comment]
Hey @sumitkr2000 I want to work on this issue. Kindly assign me this. Thank you !

**Comment by sumitkr2000** [comment]
@ShrutiSingh04503 i am not pa
