### ISSUE TITLE
Whole Content is neither centered nor well structured

### ISSUE THREAD

**Issue by Iron-Thunder** [DSC-JSS-NOIDA/blogzen#8]
![image](https://github.com/DSC-JSS-NOIDA/blogzen/assets/103611908/c979d82d-7147-4a41-9240-b23f72b96227)

**Comment by Iron-Thunder** [comment]
Can i work in this issue??

**Comment by SyedImtiyaz-1** [comment]
already raised a PR Mr. @Iron-Thunder 
### CHECK #4

**Comment by Iron-Thunder** [comment]
.
