### ISSUE TITLE
[BUG] : Add Hover effect to the Login Button

### ISSUE THREAD

**Issue by Harshsaini001** [DSC-JSS-NOIDA/blogzen#808]
Add Hover effect to the Login button . So that the Login Button looks as attractive as the Signup button.

Website for this repository : https://blogzen-gdsc.netlify.app/

Uploading Recording 2023-08-15 222141.mp4…

**Comment by Ganaik2004** [comment]
i want to work on this project.please assign it to me

**Comment by ShivamMaheshwari04** [comment]
i want to work on this project.please assign it to me

**Comment by nsundriyal62** [comment]
this issue is resolved 
i have genrated a pull request.

thanks
